### ISSUE TITLE
 Lead Application

### ISSUE THREAD

**Issue by ghost** [geekscommunity/.github#7]
### Name

GAUTAM RAI

### Discord Username (if applicable)

@GAUTAM#3146 

### Additional Context

LOOKING FOR AN OPPORTUNITY TO NURTURE AND ENHANCE MY SKILLS AND TO GROW TOGETHER.

**Comment by Ajinkgupta** [comment]
hey , in which team you are interested to be head

**Comment by ghost** [comment]
WEB DEVELOPMENT . DON'T REALLY HAVE EXPERIENCE.BUT WILL LIKE TO GET THAT
EXPERIENCE WITH YOU GUYS

**Comment by Ajinkgupta** [comment]
ohk thats great ! if you can dm me on whatsapp so i can add you as lead
